logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
    show-sql: true
  #  defer-datasource-initialization: true

  #sql:
  # init:
  #  mode: always

  profiles:
    include:
      - db
      - s3