logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
    show-sql: true
    #defer-datasource-initialization: true

  #sql:
  # init:
  #  mode: always

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  profiles:
    include:
      - db
      - s3
